export type Tender = {
  id: string;
  title: string;
  price: number;
  deadline: string;
  customer: string;
  supplierCount: number;
  risk: "низкий" | "средний" | "высокий";
  affiliated: boolean;
};

export const mockTenders: Tender[] = [
  {
    id: "TND-1001",
    title: "Поставка офисной мебели",
    price: 50000,
    deadline: "2025-12-10",
    customer: "АО 'Бизнес-Центр'",
    supplierCount: 5,
    risk: "низкий",
    affiliated: false,
  },
  {
    id: "TND-1002",
    title: "IT-консалтинг и поддержка",
    price: 120000,
    deadline: "2025-12-15",
    customer: "ГК 'Инновации'",
    supplierCount: 3,
    risk: "средний",
    affiliated: false,
  },
  {
    id: "TND-1003",
    title: "Закупка медицинского оборудования",
    price: 350000,
    deadline: "2025-12-20",
    customer: "Министерство здравоохранения",
    supplierCount: 7,
    risk: "высокий",
    affiliated: true,
  },
  {
    id: "TND-1004",
    title: "Поставка строительных материалов",
    price: 80000,
    deadline: "2025-12-12",
    customer: "АО 'СтройИнвест'",
    supplierCount: 4,
    risk: "средний",
    affiliated: false,
  },
  {
    id: "TND-1005",
    title: "Обслуживание автотранспорта",
    price: 45000,
    deadline: "2025-12-18",
    customer: "ГК 'ТрансЛогистика'",
    supplierCount: 2,
    risk: "низкий",
    affiliated: false,
  },
  {
    id: "TND-1006",
    title: "Поставка лабораторного оборудования",
    price: 220000,
    deadline: "2025-12-25",
    customer: "АО 'НаучЛаб'",
    supplierCount: 6,
    risk: "высокий",
    affiliated: true,
  },
  {
    id: "TND-1007",
    title: "IT-оборудование для офиса",
    price: 95000,
    deadline: "2025-12-11",
    customer: "АО 'ТехноСфера'",
    supplierCount: 4,
    risk: "средний",
    affiliated: false,
  },
  {
    id: "TND-1008",
    title: "Канцелярские товары для госучреждений",
    price: 15000,
    deadline: "2025-12-17",
    customer: "Городской департамент образования",
    supplierCount: 8,
    risk: "низкий",
    affiliated: false,
  },
  {
    id: "TND-1009",
    title: "Поставка серверного оборудования",
    price: 300000,
    deadline: "2025-12-22",
    customer: "АО 'Цифровые Решения'",
    supplierCount: 5,
    risk: "средний",
    affiliated: true,
  },
  {
    id: "TND-1010",
    title: "Закупка спецодежды для сотрудников",
    price: 40000,
    deadline: "2025-12-19",
    customer: "АО 'ПромКомплект'",
    supplierCount: 3,
    risk: "низкий",
    affiliated: false,
  },
  // 11–20
  {
    id: "TND-1011",
    title: "Поставка программного обеспечения",
    price: 90000,
    deadline: "2025-12-13",
    customer: "АО 'СофтСервис'",
    supplierCount: 4,
    risk: "средний",
    affiliated: false,
  },
  {
    id: "TND-1012",
    title: "Техническая поддержка серверов",
    price: 70000,
    deadline: "2025-12-16",
    customer: "АО 'СерверПро'",
    supplierCount: 3,
    risk: "низкий",
    affiliated: false,
  },
  {
    id: "TND-1013",
    title: "Поставка компьютеров для школы",
    price: 120000,
    deadline: "2025-12-21",
    customer: "Школа №12",
    supplierCount: 6,
    risk: "средний",
    affiliated: false,
  },
  {
    id: "TND-1014",
    title: "Закупка мебели для библиотеки",
    price: 55000,
    deadline: "2025-12-14",
    customer: "Библиотека города Алматы",
    supplierCount: 2,
    risk: "низкий",
    affiliated: false,
  },
  {
    id: "TND-1015",
    title: "Поставка климатического оборудования",
    price: 180000,
    deadline: "2025-12-23",
    customer: "АО 'КлиматТех'",
    supplierCount: 5,
    risk: "средний",
    affiliated: true,
  },
  {
    id: "TND-1016",
    title: "Монтаж охранных систем",
    price: 95000,
    deadline: "2025-12-18",
    customer: "АО 'Безопасность'",
    supplierCount: 3,
    risk: "средний",
    affiliated: false,
  },
  {
    id: "TND-1017",
    title: "Закупка офисной техники",
    price: 130000,
    deadline: "2025-12-20",
    customer: "ГК 'ОфисПро'",
    supplierCount: 4,
    risk: "средний",
    affiliated: false,
  },
  {
    id: "TND-1018",
    title: "Поставка электроинструмента",
    price: 80000,
    deadline: "2025-12-17",
    customer: "АО 'СтройКомплект'",
    supplierCount: 6,
    risk: "средний",
    affiliated: false,
  },
  {
    id: "TND-1019",
    title: "Обслуживание ИТ-оборудования",
    price: 60000,
    deadline: "2025-12-19",
    customer: "АО 'ИТ-Сервис'",
    supplierCount: 3,
    risk: "низкий",
    affiliated: false,
  },
  {
    id: "TND-1020",
    title: "Закупка медицинских расходников",
    price: 40000,
    deadline: "2025-12-22",
    customer: "Городская поликлиника",
    supplierCount: 5,
    risk: "низкий",
    affiliated: false,
  },
  // 21–50
  {
    id: "TND-1021",
    title: "Поставка лабораторных реактивов",
    price: 120000,
    deadline: "2025-12-24",
    customer: "АО 'ЛабТех'",
    supplierCount: 4,
    risk: "средний",
    affiliated: true,
  },
  {
    id: "TND-1022",
    title: "Обслуживание серверов",
    price: 90000,
    deadline: "2025-12-21",
    customer: "АО 'СерверПро'",
    supplierCount: 3,
    risk: "низкий",
    affiliated: false,
  },
  {
    id: "TND-1023",
    title: "Поставка мебели для детсада",
    price: 50000,
    deadline: "2025-12-15",
    customer: "Детский сад №5",
    supplierCount: 2,
    risk: "низкий",
    affiliated: false,
  },
  {
    id: "TND-1024",
    title: "Закупка канцелярии",
    price: 15000,
    deadline: "2025-12-16",
    customer: "Городской департамент образования",
    supplierCount: 7,
    risk: "низкий",
    affiliated: false,
  },
  {
    id: "TND-1025",
    title: "IT-консалтинг для школы",
    price: 100000,
    deadline: "2025-12-18",
    customer: "Школа №7",
    supplierCount: 3,
    risk: "средний",
    affiliated: false,
  },
  {
    id: "TND-1026",
    title: "Поставка серверного оборудования",
    price: 300000,
    deadline: "2025-12-23",
    customer: "АО 'Цифровые Решения'",
    supplierCount: 5,
    risk: "средний",
    affiliated: true,
  },
  {
    id: "TND-1027",
    title: "Монтаж кондиционеров",
    price: 80000,
    deadline: "2025-12-19",
    customer: "АО 'КлиматТех'",
    supplierCount: 4,
    risk: "средний",
    affiliated: false,
  },
  {
    id: "TND-1028",
    title: "Обслуживание ИТ-периферии",
    price: 60000,
    deadline: "2025-12-20",
    customer: "АО 'ИТ-Сервис'",
    supplierCount: 3,
    risk: "низкий",
    affiliated: false,
  },
  {
    id: "TND-1029",
    title: "Закупка спецодежды",
    price: 40000,
    deadline: "2025-12-21",
    customer: "АО 'ПромКомплект'",
    supplierCount: 3,
    risk: "низкий",
    affiliated: false,
  },
  {
    id: "TND-1030",
    title: "Поставка строительных материалов",
    price: 90000,
    deadline: "2025-12-22",
    customer: "АО 'СтройИнвест'",
    supplierCount: 5,
    risk: "средний",
    affiliated: false,
  },
  {
    id: "TND-1031",
    title: "Обслуживание автотранспорта",
    price: 45000,
    deadline: "2025-12-23",
    customer: "ГК 'ТрансЛогистика'",
    supplierCount: 2,
    risk: "низкий",
    affiliated: false,
  },
  {
    id: "TND-1032",
    title: "IT-оборудование для офиса",
    price: 95000,
    deadline: "2025-12-24",
    customer: "АО 'ТехноСфера'",
    supplierCount: 4,
    risk: "средний",
    affiliated: false,
  },
  {
    id: "TND-1033",
    title: "Поставка лабораторного оборудования",
    price: 220000,
    deadline: "2025-12-25",
    customer: "АО 'НаучЛаб'",
    supplierCount: 6,
    risk: "высокий",
    affiliated: true,
  },
  {
    id: "TND-1034",
    title: "Закупка медицинских расходников",
    price: 40000,
    deadline: "2025-12-26",
    customer: "Городская поликлиника",
    supplierCount: 5,
    risk: "низкий",
    affiliated: false,
  },
  {
    id: "TND-1035",
    title: "Поставка компьютеров для школы",
    price: 120000,
    deadline: "2025-12-27",
    customer: "Школа №12",
    supplierCount: 6,
    risk: "средний",
    affiliated: false,
  },
  {
    id: "TND-1036",
    title: "Монтаж охранных систем",
    price: 95000,
    deadline: "2025-12-28",
    customer: "АО 'Безопасность'",
    supplierCount: 3,
    risk: "средний",
    affiliated: false,
  },
  {
    id: "TND-1037",
    title: "Поставка электроинструмента",
    price: 80000,
    deadline: "2025-12-29",
    customer: "АО 'СтройКомплект'",
    supplierCount: 6,
    risk: "средний",
    affiliated: false,
  },
  {
    id: "TND-1038",
    title: "Закупка канцелярии",
    price: 15000,
    deadline: "2025-12-30",
    customer: "Городской департамент образования",
    supplierCount: 7,
    risk: "низкий",
    affiliated: false,
  },
  {
    id: "TND-1039",
    title: "IT-консалтинг для школы",
    price: 100000,
    deadline: "2025-12-31",
    customer: "Школа №7",
    supplierCount: 3,
    risk: "средний",
    affiliated: false,
  },
  {
    id: "TND-1040",
    title: "Поставка серверного оборудования",
    price: 300000,
    deadline: "2026-01-02",
    customer: "АО 'Цифровые Решения'",
    supplierCount: 5,
    risk: "средний",
    affiliated: true,
  },
  {
    id: "TND-1041",
    title: "Монтаж кондиционеров",
    price: 80000,
    deadline: "2026-01-03",
    customer: "АО 'КлиматТех'",
    supplierCount: 4,
    risk: "средний",
    affiliated: false,
  },
  {
    id: "TND-1042",
    title: "Обслуживание ИТ-периферии",
    price: 60000,
    deadline: "2026-01-04",
    customer: "АО 'ИТ-Сервис'",
    supplierCount: 3,
    risk: "низкий",
    affiliated: false,
  },
  {
    id: "TND-1043",
    title: "Закупка спецодежды",
    price: 40000,
    deadline: "2026-01-05",
    customer: "АО 'ПромКомплект'",
    supplierCount: 3,
    risk: "низкий",
    affiliated: false,
  },
  {
    id: "TND-1044",
    title: "Поставка строительных материалов",
    price: 90000,
    deadline: "2026-01-06",
    customer: "АО 'СтройИнвест'",
    supplierCount: 5,
    risk: "средний",
    affiliated: false,
  },
  {
    id: "TND-1045",
    title: "Обслуживание автотранспорта",
    price: 45000,
    deadline: "2026-01-07",
    customer: "ГК 'ТрансЛогистика'",
    supplierCount: 2,
    risk: "низкий",
    affiliated: false,
  },
  {
    id: "TND-1046",
    title: "IT-оборудование для офиса",
    price: 95000,
    deadline: "2026-01-08",
    customer: "АО 'ТехноСфера'",
    supplierCount: 4,
    risk: "средний",
    affiliated: false,
  },
  {
    id: "TND-1047",
    title: "Поставка лабораторного оборудования",
    price: 220000,
    deadline: "2026-01-09",
    customer: "АО 'НаучЛаб'",
    supplierCount: 6,
    risk: "высокий",
    affiliated: true,
  },
  {
    id: "TND-1048",
    title: "Закупка медицинских расходников",
    price: 40000,
    deadline: "2026-01-10",
    customer: "Городская поликлиника",
    supplierCount: 5,
    risk: "низкий",
    affiliated: false,
  },
  {
    id: "TND-1049",
    title: "Поставка компьютеров для школы",
    price: 120000,
    deadline: "2026-01-11",
    customer: "Школа №12",
    supplierCount: 6,
    risk: "средний",
    affiliated: false,
  },
  {
    id: "TND-1050",
    title: "Монтаж охранных систем",
    price: 95000,
    deadline: "2026-01-12",
    customer: "АО 'Безопасность'",
    supplierCount: 3,
    risk: "средний",
    affiliated: false,
  },
];
